[package]
name = "dfir-esedb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
binrw = "0.14.0"
getset = "0.1.2"
thiserror = "1.0.63"
